### ISSUE TITLE
Trigger build based on PR comment

### ISSUE THREAD

**Issue by llaine** [llaine/hans-landa#5]
**Acceptance criteria**

Given a PR opened 
When the user is commenting on the PR and entering a specific command
Then he should be able to trigger a build immediately

**Example**
```ts
@hans-landa build now
```

**Comment by ahanriat** [comment]
### Idea 1 💡 

`@hans <projectId> <workflow> [delay: '1h' | 'tonight' | '1w']`

For the delay properties we don't have to add it now. It will be retro compatible API anyway.

### Idea2 
Based on the idea 1, the `projectId` and the `workflow` could be quite painful to remember. It would probably be better to alias them:

`@hans buildQA [delay: '1h' | 'tonight' | '1w']`

It would be nice to be able to use this alias to trigger multiple builds (ios & android for example)

**Comment by llaine** [comment]
I like the idea 2 better.
IMO the goal would be to bypass the triggers from the GitHub actions and trigger it manually for the current PR.

**Comment by llaine** [comment]
wef

**Comment by llaine** [comment]
test

**Comment by llaine** [comment]
Entry workflow
```yaml
   workflows:
            - :
              name: buildQA
              bitrise_app_slug: ca04e0425716e1ce
              bitrise_build_trigger_token: Gs7vZtsWEz-UZ_vNdNxDIA
              build_on: command
            - :
              name: buildQA
              bitrise_app_slug: ca04e0425716e1ceff
              bitrise_build_trigger_token: Gs7vZtsWEz-UZ_vNdNxDIAaaa
              build_on: command
            - :
              name: primary
              bitrise_app_slug: ca04e0425716e1ce
              bitrise_build_trigger_token: Gs7vZtsWEz-UZ_vNdNxDIA
              build_on: [commit, command]
```
